"""PDF generation for the formal complaint letter.

Urdu shaping: Noto Nastaliq Urdu is a modern OpenType font shaped via GSUB
rules, so we use fpdf2's native HarfBuzz text shaping (set_text_shaping) with
RTL direction — NOT legacy arabic_reshaper presentation forms, which this font
has no glyphs for.
"""

import logging
from pathlib import Path

from fpdf import FPDF
from fpdf.enums import TextDirection

logger = logging.getLogger("haqdar.pdf")

FONT_PATH = Path(__file__).resolve().parent.parent / "assets" / "fonts" / "NotoNastaliqUrdu.ttf"


def build_letter_pdf(
    *,
    reference_id: str,
    complaint_letter: str,
    law_reference: str,
    authority: str,
    db_version: str,
    generated_date: str,
) -> bytes:
    pdf = FPDF(format="A4")
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    has_urdu_font = FONT_PATH.exists()
    if has_urdu_font:
        pdf.add_font("Nastaliq", "", str(FONT_PATH))

    # Header band — dark charcoal with gold accents, matching the HaqDar UI theme
    pdf.set_fill_color(15, 13, 10)          # near-black charcoal
    pdf.rect(0, 0, 210, 28, style="F")
    pdf.set_fill_color(212, 175, 55)        # gold accent rule under the band
    pdf.rect(0, 28, 210, 1.2, style="F")
    pdf.set_xy(12, 8)
    pdf.set_text_color(212, 175, 55)        # gold
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 6, "HAQDAR AI", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(12)
    pdf.set_text_color(232, 220, 190)       # warm ivory
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, "Your Rights. Your Voice. Your Proof.", new_x="LMARGIN", new_y="NEXT")

    # Meta block
    pdf.set_text_color(60, 60, 60)
    pdf.set_xy(12, 36)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Reference: {reference_id}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(12)
    pdf.cell(0, 6, f"Date: {generated_date}", new_x="LMARGIN", new_y="NEXT")

    def _has_non_latin(text: str) -> bool:
        # any character outside latin-1 (e.g. Urdu/Arabic) would crash Helvetica
        try:
            text.encode("latin-1")
            return False
        except UnicodeEncodeError:
            return True

    def _meta_line(label_latin: str, value: str) -> None:
        """Render 'Label: value'. If the value contains Urdu, draw the value with
        the Nastaliq font (RTL-shaped) so it never crashes Helvetica."""
        if not value:
            return
        pdf.set_x(12)
        if has_urdu_font and _has_non_latin(value):
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(0, 6, f"{label_latin}:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_x(12)
            pdf.set_font("Nastaliq", "", 11)
            pdf.set_text_shaping(use_shaping_engine=True, direction=TextDirection.RTL, script="arab", language="urd")
            pdf.multi_cell(0, 8, value, align="R", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_shaping(False)
            pdf.set_font("Helvetica", "", 10)
        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, f"{label_latin}: {value}")

    _meta_line("Law", law_reference)
    _meta_line("Authority", authority)
    pdf.ln(2)
    pdf.set_draw_color(212, 175, 55)
    pdf.line(12, pdf.get_y(), 198, pdf.get_y())
    pdf.ln(6)

    # Letter body — native HarfBuzz shaping, RTL
    pdf.set_text_color(20, 20, 20)
    if has_urdu_font:
        pdf.set_font("Nastaliq", "", 13)
        pdf.set_text_shaping(use_shaping_engine=True, direction=TextDirection.RTL, script="arab", language="urd")
        for raw_line in complaint_letter.split("\n"):
            line = raw_line.strip()
            if not line:
                pdf.ln(5)
                continue
            pdf.multi_cell(0, 12, line, align="R", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_shaping(False)
    else:
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 7, complaint_letter)

    # Footer disclaimer
    pdf.set_y(-24)
    pdf.set_draw_color(212, 175, 55)
    pdf.line(12, pdf.get_y(), 198, pdf.get_y())
    pdf.ln(2)
    pdf.set_text_color(120, 120, 120)
    pdf.set_font("Helvetica", "", 8)
    pdf.multi_cell(
        0, 4,
        f"Generated by HaqDar AI - Database version {db_version}. "
        "This is a draft complaint for citizen use; for high-stakes cases, "
        "verify with a lawyer or the district free legal aid committee.",
        align="C",
    )

    return bytes(pdf.output())